### ISSUE TITLE
Unreliable connection after mower firmware update

### ISSUE THREAD

**Issue by Iridahonda** [alistair23/AutoMower-BLE#25]
My 405x updated to the latest firmware today and it killed the bluetooth communication.  It still pairs ok but fails to authenticate 9 times out of 10 after the paring period ends.

2024-04-28 21:02:04,450 __main__ INFO: starting scan...
2024-04-28 21:02:04,451 __main__ INFO: connecting to device...
2024-04-28 21:02:04,864 __main__ INFO: connected
2024-04-28 21:02:04,865 __main__ INFO: pairing device...
Traceback (most recent call last):
  File "/root/AutoMower-BLE/automower_ble/mower.py", line 578, in <module>
    asyncio.run(main(mower))
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/root/AutoMower-BLE/automower_ble/mower.py", line 477, in main
    await mower.connect(device)
  File "/root/AutoMower-BLE/automower_ble/mower.py", line 164, in connect
    await self.client.pair()
  File "/usr/local/lib/python3.11/dist-packages/bleak/__init__.py", line 629, in pair
    return await self._backend.pair(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/bleak/backends/bluezdbus/client.py", line 473, in pair
    assert_reply(reply)
  File "/usr/local/lib/python3.11/dist-packages/bleak/backends/bluezdbus/utils.py", line 22, in assert_reply
    raise BleakDBusError(reply.error_name, reply.body)
bleak.exc.BleakDBusError: [org.bluez.Error.AuthenticationFailed] Authentication Failed

**Comment by Iridahonda** [comment]
Please ignore this.  I upgraded to Bluez 5.66 and paried through bluetoothctl and now its working reliably again.
