### ISSUE TITLE
Easilife Go 500 - initial connection OK but then authentication errors

### ISSUE THREAD

**Issue by andyb2000** [alistair23/AutoMower-BLE#51]
Hi,
Hope it's ok to re-open. I've finally had time to work on debugging this device.
Device is a Flymo Easilife GO 500
![image](https://github.com/alistair23/AutoMower-BLE/assets/1208595/4dfa6ee1-54e1-47b7-9236-7406aefc37d8)

Doing testing using the command line:
```
python3 ble_scanner.py 
Scanning for 15.0 seconds, please wait...
Husqvarna device(s) found!

Address: 60:98:66:83:69:C5
        Name: EasiLife GO 500
        Signal Strength: -45 dBm (closer to 0 is stronger)
Traceback (most recent call last):
  File "/home/browna/Development/AutoMower-BLE/ble_scanner.py", line 60, in <module>
    asyncio.run(main(args))
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/browna/Development/AutoMower-BLE/ble_scanner.py", line 25, in main
    if list(a.manufacturer_data.keys())[0] == 0x0426 or args.show_all:
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

``` 

But when I test connecting to it, I can get a connection without PIN requirement. This can take a few attempts as the device seems very intermittent with it's BLE connection

```
python3 -m automower_ble.mower --address 60:98:66:83:69:C5
2024-05-16 17:05:37,779 automower_ble.protocol INFO: starting scan...
2024-05-16 17:05:37,780 automower_ble.protocol INFO: connecting to device...
2024-05-16 17:05:38,500 automower_ble.protocol INFO: connected
2024-05-16 17:05:38,501 automower_ble.protocol INFO: pairing device...
2024-05-16 17:05:39,310 automower_ble.protocol INFO: paired
2024-05-16 17:05:39,311 automower_ble.protocol INFO: [Service] 98bd0001-0b0e-421a-84e5-ddbf75dc6de4 (Handle: 9): Unknown
2024-05-16 17:05:44,568 automower_ble.protocol INFO: Writing: b'02fd160000000000002e14b63b6047000000004d61696e001203'
2024-05-16 17:05:44,782 automower_ble.protocol INFO: Received: b'02fd0d0000000000006315b63b6047b603'
2024-05-16 17:05:44,782 automower_ble.protocol INFO: Final response: b'02fd0d0000000000006315b63b6047b603'
2024-05-16 17:05:44,782 automower_ble.protocol INFO: Writing: b'02fd0a00b63b6047008f08012803'
2024-05-16 17:05:44,875 automower_ble.protocol INFO: Received: b'02fd0b00b63b604700b20901011403'
2024-05-16 17:05:44,875 automower_ble.protocol INFO: Final response: b'02fd0b00b63b604700b20901011403'
2024-05-16 17:05:44,875 automower_ble.protocol INFO: Writing: b'02fd1000b63b604701a100af5a1209000000b703'
2024-05-16 17:05:44,966 automower_ble.protocol INFO: Received: b'02fd1300b63b604701e601af5a1209000002001e'
2024-05-16 17:05:44,967 automower_ble.protocol INFO: Received: b'051b03'
2024-05-16 17:05:44,967 automower_ble.protocol INFO: Final response: b'02fd1300b63b604701e601af5a1209000002001e051b03'
Mower manufacturer: Flymo
2024-05-16 17:05:44,968 automower_ble.protocol INFO: Writing: b'02fd1000b63b604701a100af5a1209000000b703'
2024-05-16 17:05:45,058 automower_ble.protocol INFO: Received: b'02fd1300b63b604701e601af5a1209000002001e'
2024-05-16 17:05:45,059 automower_ble.protocol INFO: Received: b'051b03'
2024-05-16 17:05:45,059 automower_ble.protocol INFO: Final response: b'02fd1300b63b604701e601af5a1209000002001e051b03'
Mower model: Easilife Go 500
2024-05-16 17:05:45,059 automower_ble.protocol INFO: Writing: b'02fd1000b63b604701a100af0a10150000003003'
2024-05-16 17:05:45,147 automower_ble.protocol INFO: Received: b'02fd1200b63b604701db01af0a10150000010000'
2024-05-16 17:05:45,147 automower_ble.protocol INFO: Received: b'4803'
2024-05-16 17:05:45,147 automower_ble.protocol INFO: Final response: b'02fd1200b63b604701db01af0a101500000100004803'
Mower is not charging
2024-05-16 17:05:45,148 automower_ble.protocol INFO: Writing: b'02fd1000b63b604701a100af0a1014000000bf03'
2024-05-16 17:05:45,233 automower_ble.protocol INFO: Received: b'02fd1200b63b604701db01af0a10140000010064'
2024-05-16 17:05:45,235 automower_ble.protocol INFO: Received: b'7b03'
2024-05-16 17:05:45,235 automower_ble.protocol INFO: Final response: b'02fd1200b63b604701db01af0a101400000100647b03'
Battery is: 100%
2024-05-16 17:05:45,235 automower_ble.protocol INFO: Writing: b'02fd1000b63b604701a100afea11020000006a03'
2024-05-16 17:05:45,322 automower_ble.protocol INFO: Received: b'02fd1200b63b604701db01afea11020000010002'
2024-05-16 17:05:45,323 automower_ble.protocol INFO: Received: b'6403'
2024-05-16 17:05:45,323 automower_ble.protocol INFO: Final response: b'02fd1200b63b604701db01afea110200000100026403'
Mower state: MowerState.STOPPED
2024-05-16 17:05:45,323 automower_ble.protocol INFO: Writing: b'02fd1000b63b604701a100afea1103000000e503'
2024-05-16 17:05:45,416 automower_ble.protocol INFO: Received: b'02fd1200b63b604701db01afea11030000010000'
2024-05-16 17:05:45,418 automower_ble.protocol INFO: Received: b'ef03'
2024-05-16 17:05:45,418 automower_ble.protocol INFO: Final response: b'02fd1200b63b604701db01afea11030000010000ef03'
Mower activity: MowerActivity.NONE
2024-05-16 17:05:45,418 automower_ble.protocol INFO: Writing: b'02fd1000b63b604701a100af321201000000c903'
2024-05-16 17:05:45,501 automower_ble.protocol INFO: Received: b'02fd1500b63b6047016801af32120100000400a8'
2024-05-16 17:05:45,503 automower_ble.protocol INFO: Received: b'3147662703'
2024-05-16 17:05:45,503 automower_ble.protocol INFO: Final response: b'02fd1500b63b6047016801af32120100000400a83147662703'
Next start time: 2024-05-17 10:30:00
2024-05-16 17:05:45,503 automower_ble.protocol INFO: Writing: b'02fd1000b63b604701a100af761200000000ef03'
2024-05-16 17:05:45,593 automower_ble.protocol INFO: Received: b'02fd2d00b63b6047018d01af76120000001c001f'
2024-05-16 17:05:45,595 automower_ble.protocol INFO: Received: b'a823000fdf210019910b00849701009626000018'
2024-05-16 17:05:45,596 automower_ble.protocol INFO: Received: b'0100000fdf21006103'
2024-05-16 17:05:45,597 automower_ble.protocol INFO: Final response: b'02fd2d00b63b6047018d01af76120000001c001fa823000fdf210019910b008497010096260000180100000fdf21006103'
totalRunningTime 2336799
totalCuttingTime 2219791
totalChargingTime 758041
totalSearchingTime 104324
numberOfCollisions 9878
numberOfChargingCycles 280
cuttingBladeUsageTime 2219791
2024-05-16 17:05:45,597 automower_ble.protocol INFO: Writing: b'02fd1000b63b604701a100af5a120a0000003f03'
2024-05-16 17:05:45,681 automower_ble.protocol INFO: Received: b'02fd1500b63b6047016801af5a120a00000400d8'
2024-05-16 17:05:45,683 automower_ble.protocol INFO: Received: b'ef9c0c3803'
2024-05-16 17:05:45,683 automower_ble.protocol INFO: Final response: b'02fd1500b63b6047016801af5a120a00000400d8ef9c0c3803'
Serial number: 211611608
2024-05-16 17:05:45,683 automower_ble.protocol INFO: Writing: b'02fd1400b63b6047015500af7a1201000400000000007903'
2024-05-16 17:05:45,777 automower_ble.protocol INFO: Received: b'02fd1a00b63b6047012a01af7a120100000900e7'
2024-05-16 17:05:45,778 automower_ble.protocol INFO: Received: b'fd416609000000022c03'
2024-05-16 17:05:45,778 automower_ble.protocol INFO: Final response: b'02fd1a00b63b6047012a01af7a120100000900e7fd416609000000022c03'
Last message: 
        2024-05-13 11:47:51
        TRAPPED
2024-05-16 17:05:45,780 automower_ble.protocol INFO: disconnecting...
2024-05-16 17:05:47,793 automower_ble.protocol INFO: disconnected
browna@aspire-laptop:~/Development/AutoMower-BLE$ python3 -m automower_ble.mower --address 60:98:66:83:69:C5
Unable to connect to device address: 60:98:66:83:69:C5
Please make sure the device address is correct, the device is powered on and nearby
browna@aspire-laptop:~/Development/AutoMower-BLE$ python3 -m automower_ble.mower --address 60:98:66:83:69:C5
2024-05-16 17:15:26,090 automower_ble.protocol INFO: starting scan...
2024-05-16 17:15:26,091 automower_ble.protocol INFO: connecting to device...
2024-05-16 17:15:27,141 automower_ble.protocol INFO: connected
2024-05-16 17:15:27,142 automower_ble.protocol INFO: pairing device...
2024-05-16 17:15:27,146 automower_ble.protocol INFO: paired
2024-05-16 17:15:27,146 automower_ble.protocol INFO: [Service] 98bd0001-0b0e-421a-84e5-ddbf75dc6de4 (Handle: 9): Unknown
2024-05-16 17:15:32,428 automower_ble.protocol INFO: Writing: b'02fd160000000000002e14b63b6047000000004d61696e001203'
2024-05-16 17:15:32,634 automower_ble.protocol INFO: Received: b'02fd0d0000000000006315b63b6047b603'
2024-05-16 17:15:32,634 automower_ble.protocol INFO: Final response: b'02fd0d0000000000006315b63b6047b603'
2024-05-16 17:15:32,635 automower_ble.protocol INFO: Writing: b'02fd0a00b63b6047008f08012803'
2024-05-16 17:15:32,726 automower_ble.protocol INFO: Received: b'02fd0b00b63b604700b20901011403'
2024-05-16 17:15:32,726 automower_ble.protocol INFO: Final response: b'02fd0b00b63b604700b20901011403'
2024-05-16 17:15:32,727 automower_ble.protocol INFO: Writing: b'02fd1000b63b604701a100af5a1209000000b703'
2024-05-16 17:15:32,814 automower_ble.protocol INFO: Received: b'02fd1300b63b604701e601af5a1209000002001e'
2024-05-16 17:15:32,815 automower_ble.protocol INFO: Received: b'051b03'
2024-05-16 17:15:32,815 automower_ble.protocol INFO: Final response: b'02fd1300b63b604701e601af5a1209000002001e051b03'
Mower manufacturer: Flymo
2024-05-16 17:15:32,816 automower_ble.protocol INFO: Writing: b'02fd1000b63b604701a100af5a1209000000b703'
2024-05-16 17:15:32,906 automower_ble.protocol INFO: Received: b'02fd1300b63b604701e601af5a1209000002001e'
2024-05-16 17:15:32,908 automower_ble.protocol INFO: Received: b'051b03'
2024-05-16 17:15:32,908 automower_ble.protocol INFO: Final response: b'02fd1300b63b604701e601af5a1209000002001e051b03'
Mower model: Easilife Go 500
2024-05-16 17:15:32,909 automower_ble.protocol INFO: Writing: b'02fd1000b63b604701a100af0a10150000003003'
2024-05-16 17:15:32,994 automower_ble.protocol INFO: Received: b'02fd1200b63b604701db01af0a10150000010000'
2024-05-16 17:15:32,996 automower_ble.protocol INFO: Received: b'4803'
2024-05-16 17:15:32,996 automower_ble.protocol INFO: Final response: b'02fd1200b63b604701db01af0a101500000100004803'
Mower is not charging
2024-05-16 17:15:32,997 automower_ble.protocol INFO: Writing: b'02fd1000b63b604701a100af0a1014000000bf03'
2024-05-16 17:15:33,086 automower_ble.protocol INFO: Received: b'02fd1200b63b604701db01af0a10140000010064'
2024-05-16 17:15:33,087 automower_ble.protocol INFO: Received: b'7b03'
2024-05-16 17:15:33,088 automower_ble.protocol INFO: Final response: b'02fd1200b63b604701db01af0a101400000100647b03'
Battery is: 100%
2024-05-16 17:15:33,088 automower_ble.protocol INFO: Writing: b'02fd1000b63b604701a100afea11020000006a03'
2024-05-16 17:15:33,174 automower_ble.protocol INFO: Received: b'02fd1200b63b604701db01afea11020000010002'
2024-05-16 17:15:33,176 automower_ble.protocol INFO: Received: b'6403'
2024-05-16 17:15:33,177 automower_ble.protocol INFO: Final response: b'02fd1200b63b604701db01afea110200000100026403'
Mower state: MowerState.STOPPED
2024-05-16 17:15:33,177 automower_ble.protocol INFO: Writing: b'02fd1000b63b604701a100afea1103000000e503'
2024-05-16 17:15:33,266 automower_ble.protocol INFO: Received: b'02fd1200b63b604701db01afea11030000010000'
2024-05-16 17:15:33,268 automower_ble.protocol INFO: Received: b'ef03'
2024-05-16 17:15:33,269 automower_ble.protocol INFO: Final response: b'02fd1200b63b604701db01afea11030000010000ef03'
Mower activity: MowerActivity.NONE
2024-05-16 17:15:33,270 automower_ble.protocol INFO: Writing: b'02fd1000b63b604701a100af321201000000c903'
2024-05-16 17:15:33,354 automower_ble.protocol INFO: Received: b'02fd1500b63b6047016801af32120100000400a8'
2024-05-16 17:15:33,355 automower_ble.protocol INFO: Received: b'3147662703'
2024-05-16 17:15:33,356 automower_ble.protocol INFO: Final response: b'02fd1500b63b6047016801af32120100000400a83147662703'
Next start time: 2024-05-17 10:30:00
2024-05-16 17:15:33,357 automower_ble.protocol INFO: Writing: b'02fd1000b63b604701a100af761200000000ef03'
2024-05-16 17:15:33,446 automower_ble.protocol INFO: Received: b'02fd2d00b63b6047018d01af76120000001c001f'
2024-05-16 17:15:33,447 automower_ble.protocol INFO: Received: b'a823000fdf210019910b00849701009626000018'
2024-05-16 17:15:33,449 automower_ble.protocol INFO: Received: b'0100000fdf21006103'
2024-05-16 17:15:33,450 automower_ble.protocol INFO: Final response: b'02fd2d00b63b6047018d01af76120000001c001fa823000fdf210019910b008497010096260000180100000fdf21006103'
totalRunningTime 2336799
totalCuttingTime 2219791
totalChargingTime 758041
totalSearchingTime 104324
numberOfCollisions 9878
numberOfChargingCycles 280
cuttingBladeUsageTime 2219791
2024-05-16 17:15:33,450 automower_ble.protocol INFO: Writing: b'02fd1000b63b604701a100af5a120a0000003f03'
2024-05-16 17:15:33,534 automower_ble.protocol INFO: Received: b'02fd1500b63b6047016801af5a120a00000400d8'
2024-05-16 17:15:33,535 automower_ble.protocol INFO: Received: b'ef9c0c3803'
2024-05-16 17:15:33,536 automower_ble.protocol INFO: Final response: b'02fd1500b63b6047016801af5a120a00000400d8ef9c0c3803'
Serial number: 211611608
2024-05-16 17:15:33,536 automower_ble.protocol INFO: Writing: b'02fd1400b63b6047015500af7a1201000400000000007903'
2024-05-16 17:15:33,670 automower_ble.protocol INFO: Received: b'02fd1a00b63b6047012a01af7a120100000900e7'
2024-05-16 17:15:33,671 automower_ble.protocol INFO: Received: b'fd416609000000022c03'
2024-05-16 17:15:33,671 automower_ble.protocol INFO: Final response: b'02fd1a00b63b6047012a01af7a120100000900e7fd416609000000022c03'
Last message: 
        2024-05-13 11:47:51
        TRAPPED
2024-05-16 17:15:33,676 automower_ble.protocol INFO: disconnecting...
2024-05-16 17:15:35,781 automower_ble.protocol INFO: disconnected

``` 

So that looks good news!
I have setup my BLE client in esphome:

```
esp32_ble_tracker:
  scan_parameters:
    active: false
    continuous: false
    duration: 50sec

bluetooth_proxy:
  active: true
  cache_services: true

external_components:
  - source: github://pr#6596
    components: [ bluetooth_proxy, esp32_ble_client ]
``` 

Then add the integration with the MAC address. Again takes a few attempts, powering on and off mower but eventually it adds and creates entities:

![image](https://github.com/alistair23/AutoMower-BLE/assets/1208595/d732063c-1f26-49e8-819d-49694dca9ed4)

However, almost immediately after adding, it no longer communicates (I think this is when the 3 minute BLE discovery of the mower expires possibly) and I start to get Authentication Failed in the logs, no commands are executed and no further status updates are found in Home Assistant (The entry is just stuck, no changes, no updates just sits on the last communication it got from the mower)

Logs:

```
bleak.exc.BleakError: mower-ble [A8:42:E3:CB:8B:F4]: None - 60:98:66:83:69:C5 is not connected

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 315, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/husqvarna_automower_ble/coordinator.py", line 102, in _async_update_data
    await self._async_find_device()
  File "/config/custom_components/husqvarna_automower_ble/coordinator.py", line 69, in _async_find_device
    if not await self.mower.connect(device):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/automower_ble/protocol.py", line 366, in connect
    await self.client.pair()
  File "/usr/local/lib/python3.12/site-packages/bleak/__init__.py", line 629, in pair
    return await self._backend.pair(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/bleak/backends/bluezdbus/client.py", line 473, in pair
    assert_reply(reply)
  File "/usr/local/lib/python3.12/site-packages/bleak/backends/bluezdbus/utils.py", line 22, in assert_reply
    raise BleakDBusError(reply.error_name, reply.body)
bleak.exc.BleakDBusError: [org.bluez.Error.AuthenticationFailed] Authentication Failed
2024-05-16 17:30:17.429 DEBUG (MainThread) [custom_components.husqvarna_automower_ble] Finished fetching Husqvarna Automower BLE Data Update Coordinator data in 12.043 seconds (success: False)
2024-05-16 17:30:17.430 DEBUG (MainThread) [custom_components.husqvarna_automower_ble.lawn_mower] AutomowerLawnMower: _handle_coordinator_update
2024-05-16 17:30:17.430 DEBUG (MainThread) [custom_components.husqvarna_automower_ble.lawn_mower] BatterySensor: _handle_coordinator_update
2024-05-16 17:30:25.392 ERROR (MainThread) [automower_ble.protocol] Unable to get response from device: '60:98:66:83:69:C5'
2024-05-16 17:30:25.392 ERROR (MainThread) [custom_components.husqvarna_automower_ble.coordinator] Error getting data from device
2024-05-16 17:30:25.393 DEBUG (MainThread) [custom_components.husqvarna_automower_ble.coordinator] Trying to reconnect
2024-05-16 17:30:26.874 ERROR (MainThread) [custom_components.husqvarna_automower_ble] Unexpected error fetching Husqvarna Automower BLE Data Update Coordinator data
Traceback (most recent call last):
  File "/config/custom_components/husqvarna_automower_ble/coordinator.py", line 82, in _async_update_data
    data["battery_level"] = await self.mower.battery_level()
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/automower_ble/mower.py", line 99, in battery_level
    return await self.get_parameter("batteryLevel")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/automower_ble/mower.py", line 47, in get_parameter
    response = await self._request_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/automower_ble/protocol.py", line 324, in _request_response
    await self._write_data(request_data)
  File "/usr/local/lib/python3.12/site-packages/automower_ble/protocol.py", line 279, in _write_data
    await self.client.write_gatt_char(self.write_char, chunk, response=False)
  File "/usr/local/lib/python3.12/site-packages/bleak/__init__.py", line 776, in write_gatt_char
    await self._backend.write_gatt_char(characteristic, data, response)
  File "/usr/local/lib/python3.12/site-packages/bleak/backends/bluezdbus/client.py", line 824, in write_gatt_char
    raise BleakError("Not connected")
bleak.exc.BleakError: Not connected

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 315, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/husqvarna_automower_ble/coordinator.py", line 102, in _async_update_data
    await self._async_find_device()
  File "/config/custom_components/husqvarna_automower_ble/coordinator.py", line 69, in _async_find_device
    if not await self.mower.connect(device):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/automower_ble/protocol.py", line 366, in connect
    await self.client.pair()
  File "/usr/local/lib/python3.12/site-packages/bleak/__init__.py", line 629, in pair
    return await self._backend.pair(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/bleak/backends/bluezdbus/client.py", line 473, in pair
    assert_reply(reply)
  File "/usr/local/lib/python3.12/site-packages/bleak/backends/bluezdbus/utils.py", line 22, in assert_reply
    raise BleakDBusError(reply.error_name, reply.body)
bleak.exc.BleakDBusError: [org.bluez.Error.AuthenticationFailed] Authentication Failed
2024-05-16 17:30:26.878 DEBUG (MainThread) [custom_components.husqvarna_automower_ble] Finished fetching Husqvarna Automower BLE Data Update Coordinator data in 20.871 seconds (success: False)
2024-05-16 17:30:26.878 DEBUG (MainThread) [custom_components.husqvarna_automower_ble.lawn_mower] AutomowerLawnMower: _handle_coordinator_update
2024-05-16 17:30:26.879 DEBUG (MainThread) [custom_components.husqvarna_automower_ble.lawn_mower] BatterySensor: _handle_coordinator_update

``` 

BUT, if I leave it, after a few minutes it will then suddenly get a slight update and display battery status again, but still not show the correct state. Below is when the unit is docked/charging:

```
bleak.exc.BleakDBusError: [org.bluez.Error.AuthenticationFailed] Authentication Failed
2024-05-16 17:50:55.639 DEBUG (MainThread) [custom_components.husqvarna_automower_ble] Finished fetching Husqvarna Automower BLE Data Update Coordinator data in 11.252 seconds (success: False)
2024-05-16 17:50:55.639 DEBUG (MainThread) [custom_components.husqvarna_automower_ble.lawn_mower] AutomowerLawnMower: _handle_coordinator_update
2024-05-16 17:50:55.639 DEBUG (MainThread) [custom_components.husqvarna_automower_ble.lawn_mower] BatterySensor: _handle_coordinator_update
2024-05-16 17:51:55.387 DEBUG (MainThread) [custom_components.husqvarna_automower_ble.coordinator] Polling device
2024-05-16 17:51:55.387 DEBUG (MainThread) [custom_components.husqvarna_automower_ble.coordinator] Trying to reconnect
2024-05-16 17:52:03.108 DEBUG (MainThread) [custom_components.husqvarna_automower_ble.coordinator] 97
2024-05-16 17:52:03.210 DEBUG (MainThread) [custom_components.husqvarna_automower_ble.coordinator] MowerActivity.PARKED
2024-05-16 17:52:03.307 DEBUG (MainThread) [custom_components.husqvarna_automower_ble.coordinator] MowerState.RESTRICTED
2024-05-16 17:52:03.307 INFO (MainThread) [custom_components.husqvarna_automower_ble] Fetching Husqvarna Automower BLE Data Update Coordinator data recovered
2024-05-16 17:52:03.307 DEBUG (MainThread) [custom_components.husqvarna_automower_ble] Finished fetching Husqvarna Automower BLE Data Update Coordinator data in 7.920 seconds (success: True)
2024-05-16 17:52:03.307 DEBUG (MainThread) [custom_components.husqvarna_automower_ble.lawn_mower] AutomowerLawnMower: _handle_coordinator_update
2024-05-16 17:52:03.307 DEBUG (MainThread) [custom_components.husqvarna_automower_ble.lawn_mower] BatterySensor: _handle_coordinator_update
2024-05-16 17:53:03.386 DEBUG (MainThread) [custom_components.husqvarna_automower_ble.coordinator] Polling device
2024-05-16 17:53:03.589 DEBUG (MainThread) [custom_components.husqvarna_automower_ble.coordinator] 98
2024-05-16 17:53:03.682 DEBUG (MainThread) [custom_components.husqvarna_automower_ble.coordinator] MowerActivity.PARKED
2024-05-16 17:53:03.796 DEBUG (MainThread) [custom_components.husqvarna_automower_ble.coordinator] MowerState.RESTRICTED
2024-05-16 17:53:03.796 DEBUG (MainThread) [custom_components.husqvarna_automower_ble] Finished fetching Husqvarna Automower BLE Data Update Coordinator data in 0.410 seconds (success: True)
2024-05-16 17:53:03.797 DEBUG (MainThread) [custom_components.husqvarna_automower_ble.lawn_mower] AutomowerLawnMower: _handle_coordinator_update
2024-05-16 17:53:03.797 DEBUG (MainThread) [custom_components.husqvarna_automower_ble.lawn_mower] BatterySensor: _handle_coordinator_update
``` 

What is the best way to proceed with this? The unit doesn't allow removal of PIN code, though it does appear to connect/pair without needing that initially. I'm unsure if that is a bug actually in the mower that it doesn't need the pin on some attempts or not!

**Comment by andyb2000** [comment]
There also seems a mismatch (which I think we suspected before in the previous issue) between what the ble co-ordinator is seeing and the state in HA.
I forced the mower to fail (moved outside guide wire/boundary), which the logs caught:

```
2024-05-16 18:39:02.386 DEBUG (MainThread) [custom_components.husqvarna_automower_ble.coordinator] Polling device
2024-05-16 18:39:02.591 DEBUG (MainThread) [custom_components.husqvarna_automower_ble.coordinator] 100
2024-05-16 18:39:02.686 DEBUG (MainThread) [custom_components.husqvarna_automower_ble.coordinator] MowerActivity.NONE
2024-05-16 18:39:02.788 DEBUG (MainThread) [custom_components.husqvarna_automower_ble.coordinator] MowerState.FATAL_ERROR
2024-05-16 18:39:02.789 INFO (MainThread) [custom_components.husqvarna_automower_ble] Fetching Husqvarna Automower BLE Data Update Coordinator data recovered
2024-05-16 18:39:02.789 DEBUG (MainThread) [custom_components.husqvarna_automower_ble] Finished fetching Husqvarna Automower BLE Data Update Coordinator data in 0.403 seconds (success: True)
2024-05-16 18:39:02.789 DEBUG (MainThread) [custom_components.husqvarna_automower_ble.lawn_mower] AutomowerLawnMower: _handle_coordinator_update
2024-05-16 18:39:02.789 DEBUG (MainThread) [custom_components.husqvarna_automower_ble.lawn_mower] BatterySensor: _handle_coordinator_update

``` 

But in HA it didn't change, it still showed "error" (Which is what it seems to say no matter what state it's in).
![image](https://github.com/alistair23/AutoMower-BLE/assets/1208595/fd9a1cfb-c92a-47e3-ad50-38e69f26f863)

**Comment by alistair23** [comment]
I'm not clear on what the issue is

**Comment by andyb2000** [comment]
Apologies, I should have been clearer/not put multiple issues into one entry. These are the current issues I'm facing and not sure the best way of solving/debugging each one.


1) **state in Home Assistant isn't reflecting the correct state**. In the home assistant logs it shows:
```
2024-05-16 17:53:03.386 DEBUG (MainThread) [custom_components.husqvarna_automower_ble.coordinator] Polling device
2024-05-16 17:53:03.589 DEBUG (MainThread) [custom_components.husqvarna_automower_ble.coordinator] 98
2024-05-16 17:53:03.682 DEBUG (MainThread) [custom_components.husqvarna_automower_ble.coordinator] MowerActivity.PARKED
2024-05-16 17:53:03.796 DEBUG (MainThread) [custom_components.husqvarna_automower_ble.coordinator] MowerState.RESTRICTED
``` 
But the Home assistant GUI shows "Error" regardless of what the activity in the logs shows:
![image](https://github.com/alistair23/AutoMower-BLE/assets/1208595/eec4d882-205d-422e-92eb-2f2d6a441df0)

2) **No commands work, either in the CLI mower.py or via Home Assistant**. I can't control or send any commands that work. If I send a command through the CLI:

3) **It seems to cycle through "Authentication Failed" and then reconnect**, is that expected behaviour due to what seems like buggy BLE code on the automower itself?

**Comment by alistair23** [comment]
> But the Home assistant GUI shows "Error" regardless of what the activity in the logs shows:

Odd. Can you add some logs to [around here](https://github.com/home-assistant/core/pull/108326/files#diff-9dff679e358c24d3de4ed60ec7d59aadc8e65f0f2c9ec74f982114755e326d9bR71) and get an idea why it isn't updating? My status updates

> 2\. **No commands work, either in the CLI mower.py or via Home Assistant**. I can't control or send any commands that work. If I send a command through the CLI:

This function is failing for some reason: https://github.com/alistair23/AutoMower-BLE/blob/a0e588d14d4065d3335c2a33ac13549ce3c3a09c/automower_ble/protocol.py

Have a look at the value and see where the decode fails. It might be something that has been fixed in main but not in the last release

>     3. **It seems to cycle through "Authentication Failed" and then reconnect**, is that expected behaviour due to what seems like buggy BLE code on the automower itself?

That's odd as well, although that might just be an issue with the HA BLE stack. It's pretty unreliable

**Comment by andyb2000** [comment]
Thanks Alistair.

Working through, I've added in debug into the HA component and think I've spotted it:

```
2024-05-17 10:08:59.698 DEBUG (MainThread) [custom_components.husqvarna_automower_ble.lawn_mower] mower state = MowerState.RESTRICTED
2024-05-17 10:08:59.698 DEBUG (MainThread) [custom_components.husqvarna_automower_ble.lawn_mower] mower activity = MowerActivity.PARKED
``` 

So my debug shows the state and activity are returning these strings:
MowerState.RESTRICTED
MowerActivity.PARKED

Ignoring case sensitivity (which does play a part, but I simply did .lower()) the match doesn't work since mine seems to retain the prefix MowerState or MowerActivity in the response.

Not sure if we should 'fix' that in the HA component, or in the library?
As a temporary test I've done this:

```
        state = str(self.coordinator.data["state"]).lower()
        activity = str(self.coordinator.data["activity"]).lower()
        state = state[state.find('.')+1:]
        activity = activity[activity.find('.')+1:]

``` 
to strip before the dot and that seemed to work. I've also added "in_operation" to the state dict as that's what my mower returns.
That's now returning the correct state into HA:

![image](https://github.com/alistair23/AutoMower-BLE/assets/1208595/510023a1-e0ea-4c17-bc1a-54080217c945)

Would you suggest we fix that in the library or the home-assistant component? Happy to do a PR to handle either way.

**Comment by alistair23** [comment]
Have you manually updated the AutoMower-BLE component?

**Comment by andyb2000** [comment]
> Have you manually updated the AutoMower-BLE component?

Yes, all modifications I've done so far are in the custom_components/husqvarna_automower_ble/lawn_mower.py

(I've not touched the library)

**Comment by alistair23** [comment]
I mean have you changed the version of the library you are using?

**Comment by andyb2000** [comment]
> I mean have you changed the version of the library you are using?

Ah, apologies. library is from git main (no changes).
So are we better to solve this in the library or the Home Assistant component? As I'll adjust my code and send a PR to suit.

**Comment by alistair23** [comment]
> Ah, apologies. library is from git main (no changes).

My PR isn't using `main` so you have changed the library. `main` isn't tested and will probably have a few issues. They do eventually need to be fixed.

The best bet is to fix them in the HA component. If you can fix them, test it and send a PR to me that will help a lot when I update the library

**Comment by andyb2000** [comment]
Thanks @alistair23 yes that was what I'd meant, the husqvarna_automower_ble branch.

I've sent a PR to the HA component that I've got tested and working here.
https://github.com/alistair23/homeassistant-core/pull/1/files

That solves my issue 1 with incorrect state.

I'll continue to try and debug why sending commands are failing.

**Comment by erikmol** [comment]
I've updated the home-assistant component to be compatible using the changes in this [commit](https://github.com/erikmol/hass-automower-ble-hacs/commit/f95f5e1e0e955e74a5ee6c468b82b33670abfed3). @alistair23 Do you really want PRs to the same branch as you are pushing to home-assistant? Maybe it would be better to have PRs to a development branch to test things out?

**Comment by alistair23** [comment]
I think a PR against the HA branch is the way to go. I probably won't merge it via GitHub, but it at least provide a list of changes that are required to support the latest library update

**Comment by andyb2000** [comment]
aha, all makes sense thank you @erikmol and @alistair23 

To keep things simple, I'll close this issue and open a single one for the command send issues. I'm terrible at confusing problems by throwing too many at a time! Sorry :)

**Comment by andyb2000** [comment]
> > I'll close this issue and open a single one for the command send issues.
> 
> There is a bug present [here](https://github.com/alistair23/AutoMower-BLE/blob/bfabfd4ea7c87a2fcc96b66a897847fb81b33e3f/automower_ble/mower.py#L57) where `response_dict` can be `None` which will be fixed within [this PR](https://github.com/alistair23/AutoMower-BLE/pull/37#issuecomment-2108726741). See this simple [change](https://github.com/erikmol/AutoMower-BLE/commit/78b74bcdee9c8af93dcc16dae41613eef14b684a) if that resolves your issue?

Thanks,
Unfortunately not, still getting an error response failed validation and no action from the mower.
I'll open in separate issue
