### ISSUE TITLE
Gardena Sileno city 250 

### ISSUE THREAD

**Issue by thibault-78** [alistair23/AutoMower-BLE#55]
Hello
thanks for your work
I tried to use it but I get some errors just after pairing:
it is a Gardena Sileno city 250, so should be already in the known models
Here are the logs,
Do you have some idea?

```
2024-05-25 10:00:21.151 DEBUG (MainThread) [custom_components.husqvarna_automower_ble] connecting to CC:B5:4C:D9:12:8E with channel ID 2681773895
2024-05-25 10:00:21.151 INFO (MainThread) [automower_ble.mower] starting scan...
2024-05-25 10:00:21.151 INFO (MainThread) [automower_ble.mower] connecting to device...
2024-05-25 10:00:21.389 INFO (MainThread) [automower_ble.mower] connected
2024-05-25 10:00:21.389 INFO (MainThread) [automower_ble.mower] pairing device...
2024-05-25 10:00:21.598 INFO (MainThread) [automower_ble.mower] paired
2024-05-25 10:00:21.598 INFO (MainThread) [automower_ble.mower] [Service] 00001800-0000-1000-8000-00805f9b34fb (Handle: 1): Generic Access Profile
2024-05-25 10:00:21.688 DEBUG (MainThread) [automower_ble.mower]   [Characteristic] 00002a00-0000-1000-8000-00805f9b34fb (Handle: 3): Device Name (read), Value: bytearray(b'Tondeuse')
2024-05-25 10:00:21.799 DEBUG (MainThread) [automower_ble.mower]   [Characteristic] 00002a01-0000-1000-8000-00805f9b34fb (Handle: 5): Appearance (read), Value: bytearray(b'\x00\x00')
2024-05-25 10:00:21.902 DEBUG (MainThread) [automower_ble.mower]   [Characteristic] 00002a04-0000-1000-8000-00805f9b34fb (Handle: 7): Peripheral Preferred Connection Parameters (read), Value: bytearray(b'P\x00\xa0\x00\x00\x00\xe8\x03')
2024-05-25 10:00:21.902 INFO (MainThread) [automower_ble.mower] [Service] 00001801-0000-1000-8000-00805f9b34fb (Handle: 8): Generic Attribute Profile
2024-05-25 10:00:21.902 INFO (MainThread) [automower_ble.mower] [Service] 98bd0001-0b0e-421a-84e5-ddbf75dc6de4 (Handle: 9): Husqvarna
2024-05-25 10:00:21.902 DEBUG (MainThread) [automower_ble.mower]   [Characteristic] 98bd0002-0b0e-421a-84e5-ddbf75dc6de4 (Handle: 11): Unknown (write-without-response)
2024-05-25 10:00:22.002 DEBUG (MainThread) [automower_ble.mower]   [Characteristic] 98bd0003-0b0e-421a-84e5-ddbf75dc6de4 (Handle: 14): Unknown (read,notify), Value: bytearray(b'')
2024-05-25 10:00:22.112 DEBUG (MainThread) [automower_ble.mower]   [Characteristic] 98bd0004-0b0e-421a-84e5-ddbf75dc6de4 (Handle: 18): Unknown (read), Value: bytearray(b'Automower\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00')
2024-05-25 10:00:27.160 INFO (MainThread) [automower_ble.mower] Writing: b'02fd160000000000002e14479fd89f000000004d61696e004803'
2024-05-25 10:00:27.161 DEBUG (MainThread) [automower_ble.mower] Finished writing
2024-05-25 10:00:37.163 ERROR (MainThread) [automower_ble.mower] Unable to get response from device: 'CC:B5:4C:D9:12:8E'
2024-05-25 10:00:37.164 INFO (MainThread) [automower_ble.mower] disconnecting...
2024-05-25 10:00:37.258 INFO (MainThread) [automower_ble.mower] disconnected
2024-05-25 10:00:37.258 INFO (MainThread) [automower_ble.mower] Writing: b'02fd160000000000002e14479fd89f000000004d61696e004803'
```

**Comment by djungelola** [comment]
Reload the HA integration a couple of times, usually solves my similar problems.

**Comment by thibault-78** [comment]
Hello @djungelola 
I have done it without sucess :(
I try to pari it juste afet power on (befoire pin code) it seems that the dialog is a little bit more advanced
Last logs are:
```
2024-05-27 19:07:10.978 DEBUG (MainThread) [custom_components.husqvarna_automower_ble] connecting to CC:B5:4C:D9:12:8E with channel ID 1989126689
2024-05-27 19:07:10.978 INFO (MainThread) [automower_ble.mower] starting scan...
2024-05-27 19:07:10.978 INFO (MainThread) [automower_ble.mower] connecting to device...
2024-05-27 19:07:12.108 INFO (MainThread) [automower_ble.mower] connected
2024-05-27 19:07:12.108 INFO (MainThread) [automower_ble.mower] pairing device...
2024-05-27 19:07:12.125 INFO (MainThread) [automower_ble.mower] paired
2024-05-27 19:07:12.126 INFO (MainThread) [automower_ble.mower] [Service] 00001800-0000-1000-8000-00805f9b34fb (Handle: 1): Generic Access Profile
2024-05-27 19:07:12.212 DEBUG (MainThread) [automower_ble.mower]   [Characteristic] 00002a00-0000-1000-8000-00805f9b34fb (Handle: 3): Device Name (read), Value: bytearray(b'Tondeuse')
2024-05-27 19:07:12.300 DEBUG (MainThread) [automower_ble.mower]   [Characteristic] 00002a01-0000-1000-8000-00805f9b34fb (Handle: 5): Appearance (read), Value: bytearray(b'\x00\x00')
2024-05-27 19:07:12.406 DEBUG (MainThread) [automower_ble.mower]   [Characteristic] 00002a04-0000-1000-8000-00805f9b34fb (Handle: 7): Peripheral Preferred Connection Parameters (read), Value: bytearray(b'P\x00\xa0\x00\x00\x00\xe8\x03')
2024-05-27 19:07:12.407 INFO (MainThread) [automower_ble.mower] [Service] 00001801-0000-1000-8000-00805f9b34fb (Handle: 8): Generic Attribute Profile
2024-05-27 19:07:12.407 INFO (MainThread) [automower_ble.mower] [Service] 98bd0001-0b0e-421a-84e5-ddbf75dc6de4 (Handle: 9): Husqvarna
2024-05-27 19:07:12.407 DEBUG (MainThread) [automower_ble.mower]   [Characteristic] 98bd0002-0b0e-421a-84e5-ddbf75dc6de4 (Handle: 11): Unknown (write-without-response)
2024-05-27 19:07:12.509 DEBUG (MainThread) [automower_ble.mower]   [Characteristic] 98bd0003-0b0e-421a-84e5-ddbf75dc6de4 (Handle: 14): Unknown (read,notify), Value: bytearray(b'\x01\x96\x03')
2024-05-27 19:07:12.617 DEBUG (MainThread) [automower_ble.mower]   [Characteristic] 98bd0004-0b0e-421a-84e5-ddbf75dc6de4 (Handle: 18): Unknown (read), Value: bytearray(b'Automower\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00')
2024-05-27 19:07:17.653 INFO (MainThread) [automower_ble.mower] Writing: b'02fd160000000000002e1421aa8f76000000004d61696e005c03'
2024-05-27 19:07:17.654 DEBUG (MainThread) [automower_ble.mower] Finished writing
2024-05-27 19:07:17.737 INFO (MainThread) [automower_ble.mower] Received: b'02fd0d000000000000631521aa8f76df03'
2024-05-27 19:07:17.737 INFO (MainThread) [automower_ble.mower] Received: b'02fd0d000000000000631521aa8f76df03'
2024-05-27 19:07:17.737 INFO (MainThread) [automower_ble.mower] Received: b'02fd0d000000000000631521aa8f76df03'
2024-05-27 19:07:17.737 INFO (MainThread) [automower_ble.mower] Received: b'02fd0d000000000000631521aa8f76df03'
2024-05-27 19:07:17.738 DEBUG (MainThread) [automower_ble.mower] Waiting for 17 bytes
2024-05-27 19:07:17.738 INFO (MainThread) [automower_ble.mower] Final response: b'02fd0d000000000000631521aa8f76df03'
2024-05-27 19:07:17.738 INFO (MainThread) [automower_ble.mower] Writing: b'02fd0a0021aa8f76007608012803'
2024-05-27 19:07:17.738 DEBUG (MainThread) [automower_ble.mower] Finished writing
2024-05-27 19:07:17.841 INFO (MainThread) [automower_ble.mower] Received: b'02fd0b0021aa8f76004b0901011403'
2024-05-27 19:07:17.841 INFO (MainThread) [automower_ble.mower] Received: b'02fd0b0021aa8f76004b0901011403'
2024-05-27 19:07:17.841 INFO (MainThread) [automower_ble.mower] Received: b'02fd0b0021aa8f76004b0901011403'
2024-05-27 19:07:17.841 INFO (MainThread) [automower_ble.mower] Received: b'02fd0b0021aa8f76004b0901011403'
2024-05-27 19:07:17.841 DEBUG (MainThread) [automower_ble.mower] Waiting for 15 bytes
2024-05-27 19:07:17.841 INFO (MainThread) [automower_ble.mower] Final response: b'02fd0b0021aa8f76004b0901011403'
2024-05-27 19:07:17.841 DEBUG (MainThread) [custom_components.husqvarna_automower_ble] connected and paired
2024-05-27 19:07:17.842 INFO (MainThread) [automower_ble.mower] Writing: b'02fd100021aa8f76015800af5a1209000000b703'
2024-05-27 19:07:17.843 DEBUG (MainThread) [automower_ble.mower] Finished writing
2024-05-27 19:07:17.942 INFO (MainThread) [automower_ble.mower] Received: b'02fd130021aa8f76011f01af5a1209000002000e'
2024-05-27 19:07:17.942 INFO (MainThread) [automower_ble.mower] Received: b'02fd130021aa8f76011f01af5a1209000002000e'
2024-05-27 19:07:17.942 INFO (MainThread) [automower_ble.mower] Received: b'02fd130021aa8f76011f01af5a1209000002000e'
2024-05-27 19:07:17.942 INFO (MainThread) [automower_ble.mower] Received: b'02fd130021aa8f76011f01af5a1209000002000e'
2024-05-27 19:07:17.942 INFO (MainThread) [automower_ble.mower] Received: b'019603'
2024-05-27 19:07:17.942 INFO (MainThread) [automower_ble.mower] Received: b'019603'
2024-05-27 19:07:17.942 INFO (MainThread) [automower_ble.mower] Received: b'019603'
2024-05-27 19:07:17.943 INFO (MainThread) [automower_ble.mower] Received: b'019603'
2024-05-27 19:07:17.943 DEBUG (MainThread) [automower_ble.mower] Waiting for 23 bytes
2024-05-27 19:07:17.943 INFO (MainThread) [automower_ble.mower] Final response: b'02fd130021aa8f76011f01af5a1209000002000e019603'
2024-05-27 19:07:17.943 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Husqvarna Automower for husqvarna_automower_ble
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 584, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/husqvarna_automower_ble/__init__.py", line 50, in async_setup_entry
    model = await mower.get_model()
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/automower_ble/mower.py", line 282, in get_model
    return self.response.decode_response_device_type(response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/automower_ble/response.py", line 78, in decode_response_device_type
    return MowerModels[(data[19], data[20])]
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
KeyError: (14, 1)
```
It seems it didn't detect the model correctly

**Comment by djungelola** [comment]
Ahhh, fails on the keyerror. Not sure if the latest code is pushed to0 PyPi. How does your manifest.json look like in custom_component? What version of requirements are you using? If on 0.1.32 change to 0.1.33.

If that doesnt work you can test options below :
1. Replace requirements in manifest.json with: "requirements": ["git+https://github.com/alistair23/AutoMower-BLE.git@main#automower-ble"],

2.  Add this to your _init_.py (line 41):

    """model = await mower.get_model()"""

    try:
        model = await mower.get_model()
    except KeyError:
        model = "Sileno City 250"

Got this from : https://github.com/alistair23/AutoMower-BLE/issues/3#issuecomment-2058918806

Start with option 1, works fine for me at least.

**Comment by thibault-78** [comment]
Hello
i'm 0.1.33
1/ not working :( I had errors durring my tests but I have lost the logs :(
2/ Work Fine :)
Many thanks for you help

**Comment by Jordanvdb** [comment]
Hi @thibault-78,

Curious how you got this code working as custom component in the first place as I have the same mower.
Did you just copy the git repo in a custom-component folder? And how do you call the python function? 
Curious because it does not seem your logs come from a terminal.

**Comment by thibault-78** [comment]
Hello @Jordanvdb 
I have done : https://github.com/home-assistant/home-assistant.io/pull/30921#issuecomment-2106905230
then modified the manifest
As sujected by @djungelola the version published didn't have the corection for the support of this model, so:
then 2/ from : https://github.com/alistair23/AutoMower-BLE/issues/55#issuecomment-2133905140
then https://github.com/alistair23/AutoMower-BLE/issues/3#issuecomment-2058918806
For the pairing, I spend lot of time to understand the order and time to get a correct pairing : but in fact, enter the pin and then directly clic on the add button.
for the log, they are coming from the  homeassitant log
Hope it will help you
