### ISSUE TITLE
"Return to dock" does not work

### ISSUE THREAD

**Issue by GitWally** [alistair23/AutoMower-BLE#7]
Hello @alistair23 
I'm testing the "Return to dock" command (from the UI)

![immagine](https://github.com/alistair23/AutoMower-BLE/assets/19230076/3c199d4b-e6d4-47db-9353-0a4066a28d08)

but it ends with "Failed to call service lawn_mower/dock. object bool can't be used in 'await' expression"

The following log is the result of the command given while 305 was mowing at less than 3m from the ESP32 BT Proxy

```
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:239
integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 6 April 2024 at 11:26:52 (3 occurrences)
Last logged: 15:46:35

[139942169576896] object bool can't be used in 'await' expression
[139941953795776] object bool can't be used in 'await' expression
[139942003557440] object bool can't be used in 'await' expression
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 239, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2543, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2580, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 971, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1043, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/husqvarna_automower_ble/lawn_mower.py", line 112, in async_start_mowing
    if not await self.coordinator.mower.is_connected():
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: object bool can't be used in 'await' expression

```

Meanwhile I see the lawn_mower.husqvarna_automower_battery_level percentage decreasing, so I assume it is communicating somehow.
In fact in the [20240407_home-assistant.log.txt](https://github.com/alistair23/AutoMower-BLE/files/14897753/20240407_home-assistant.log.txt) before and after this call I see messages about coodinator:

```
2024-04-07 15:45:12.348 DEBUG (MainThread) [custom_components.husqvarna_automower_ble.lawn_mower] AutomowerLawnMower: _handle_coordinator_update
2024-04-07 15:45:12.348 DEBUG (MainThread) [custom_components.husqvarna_automower_ble.lawn_mower] BatterySensor: _handle_coordinator_update
2024-04-07 15:46:11.802 DEBUG (MainThread) [custom_components.husqvarna_automower_ble.coordinator] Polling device
2024-04-07 15:46:11.803 INFO (MainThread) [automower_ble.mower] Writing: b'02fd1000235d7316014000af0a1014000000bf03'
2024-04-07 15:46:11.805 DEBUG (MainThread) [automower_ble.mower] Finished writing
2024-04-07 15:46:12.040 INFO (MainThread) [automower_ble.mower] Received: b'02fd1200235d7316013a01af0a10140000010033'
2024-04-07 15:46:12.041 DEBUG (MainThread) [automower_ble.mower] Waiting for 22 bytes
2024-04-07 15:46:12.042 INFO (MainThread) [automower_ble.mower] Received: b'2303'
2024-04-07 15:46:12.043 INFO (MainThread) [automower_ble.mower] Final response: b'02fd1200235d7316013a01af0a101400000100332303'
2024-04-07 15:46:12.043 DEBUG (MainThread) [custom_components.husqvarna_automower_ble.coordinator] 51
2024-04-07 15:46:12.043 INFO (MainThread) [automower_ble.mower] Writing: b'02fd1000235d7316014000afea1103000000e503'
2024-04-07 15:46:12.045 DEBUG (MainThread) [automower_ble.mower] Finished writing
2024-04-07 15:46:12.156 INFO (MainThread) [automower_ble.mower] Received: b'02fd1200235d7316013a01afea11030000010003'
2024-04-07 15:46:12.156 DEBUG (MainThread) [automower_ble.mower] Waiting for 22 bytes
2024-04-07 15:46:12.247 INFO (MainThread) [automower_ble.mower] Received: b'0d03'
2024-04-07 15:46:12.247 INFO (MainThread) [automower_ble.mower] Final response: b'02fd1200235d7316013a01afea110300000100030d03'
2024-04-07 15:46:12.247 DEBUG (MainThread) [custom_components.husqvarna_automower_ble.coordinator] mowing
2024-04-07 15:46:12.247 INFO (MainThread) [automower_ble.mower] Writing: b'02fd1000235d7316014000afea11020000006a03'
2024-04-07 15:46:12.248 DEBUG (MainThread) [automower_ble.mower] Finished writing
2024-04-07 15:46:12.367 INFO (MainThread) [automower_ble.mower] Received: b'02fd1200235d7316013a01afea11020000010006'
2024-04-07 15:46:12.367 DEBUG (MainThread) [automower_ble.mower] Waiting for 22 bytes
2024-04-07 15:46:12.369 INFO (MainThread) [automower_ble.mower] Received: b'0503'
2024-04-07 15:46:12.369 INFO (MainThread) [automower_ble.mower] Final response: b'02fd1200235d7316013a01afea110200000100060503'
2024-04-07 15:46:12.370 DEBUG (MainThread) [custom_components.husqvarna_automower_ble.coordinator] checkSafety
2024-04-07 15:46:12.370 DEBUG (MainThread) [custom_components.husqvarna_automower_ble] Finished fetching Husqvarna Automower BLE Data Update Coordinator data in 0.568 seconds (success: True)
```

Is there any other log I could provide to help investigating?
Thanks

**Comment by alistair23** [comment]
You need to update the component code from the PR. You are running out of date code which has a bug that should be fixed

**Comment by alistair23** [comment]
PS: The log is very helpful :)
