### ISSUE TITLE
GetAllStatistics - Error 'Data length mismatch. Read 28 bytes of 24'

### ISSUE THREAD

**Issue by Marcussjogren** [alistair23/AutoMower-BLE#88]
Hi,

When I am running the code on my Huqsvarna 440 I get the below error. Seems like the received data is larger than expected.

I commented line 207-209 and now it's working but I guess I'm missing the statistics.

I will try to resolve it - but I think this is out of my competence :)

Line 207 - 209:
```
#    statuses = await mower.command("GetAllStatistics")
#    for status, value in statuses.items():
#        print(status, value)
```

This was the error that I was receiving before.

```
No next start time
2024-12-16 19:31:20,940 protocol INFO: Writing: b'02fd1000b63b604701a100af761200000000ef03'
2024-12-16 19:31:21,024 protocol INFO: Received: b'02fd2900b63b6047017901af76120000001800e8'
2024-12-16 19:31:21,027 protocol INFO: Received: b'0ca6007ffe9d000b8e2700690e0800a8770000b7'
2024-12-16 19:31:21,032 protocol INFO: Received: b'0200006303'
2024-12-16 19:31:21,040 protocol INFO: Final response: b'02fd2900b63b6047017901af76120000001800e80ca6007ffe9d000b8e2700690e0800a8770000b70200006303'
Traceback (most recent call last):
  File "/home/pi/AutoMower-BLE/automower_ble/mower.py", line 299, in <module>
    asyncio.run(main(mower))
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 686, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/pi/AutoMower-BLE/automower_ble/mower.py", line 207, in main
    statuses = await mower.command("GetAllStatistics")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/AutoMower-BLE/automower_ble/mower.py", line 50, in command
    response_dict = command.parse_response(response)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/AutoMower-BLE/automower_ble/protocol.py", line 208, in parse_response
    raise ValueError(
ValueError: Data length mismatch. Read 28 bytes of 24
```

**Comment by Marcussjogren** [comment]
By the way, is there any way to keep the mower connected while developing? I must open the lid before sending the commands.

**Comment by Marcussjogren** [comment]
I was not skilled enough to understand the code really, so I did what any mechanic would have done: I removed the dpos data lenght check :)

Removed line 208-211 in protocol.py:
```
#        if dpos != len(data):
#            raise ValueError(
#                "Data length mismatch. Read %d bytes of %d" % (dpos, len(data))
#            )
```

It's working now, but I guess there was a reason for the dpos data length-check, hence I know that it might screw something up further on.

This is the output data that caused the "Read 28 bytes of 24" error:

```
No next start time
2024-12-16 20:57:30,763 protocol INFO: Writing: b'02fd1000b63b604701a100af761200000000ef03'
2024-12-16 20:57:30,847 protocol INFO: Received: b'02fd2900b63b6047017901af76120000001800e8'
2024-12-16 20:57:30,857 protocol INFO: Received: b'0ca6007ffe9d000b8e2700690e0800a8770000b7'
2024-12-16 20:57:30,863 protocol INFO: Received: b'0200006303'
2024-12-16 20:57:30,866 protocol INFO: Final response: b'02fd2900b63b6047017901af76120000001800e80ca6007ffe9d000b8e2700690e0800a8770000b70200006303'
totalRunningTime 10882280
totalCuttingTime 10354303
totalChargingTime 2592267
totalSearchingTime 527977
numberOfCollisions 30632
numberOfChargingCycles 695
cuttingBladeUsageTime 0
```

**Comment by alistair23** [comment]
Sorry, I just got back to looking at this.

I'm assuming that the decoded data `cuttingBladeUsageTime 0` is wrong, so just removing the check isn't enough to get the correct data.

What I'm assuming is happening is that your model doesn't support `cuttingBladeUsageTime`, as my 305 also has no way to know that information. So I'm guessing that the mower isn't sending the information, hence the 24 bytes. But we currently [expect it](https://github.com/alistair23/AutoMower-BLE/blob/main/automower_ble/protocol.json#L57)

So we probably need to convert `cuttingBladeUsageTime` to being optional.

My other thought, does any mower support `cuttingBladeUsageTime`? Maybe it's just best to remove it

**Comment by alistair23** [comment]
@erikmol any thoughts on removing `cuttingBladeUsageTime`? Does it work for you?

**Comment by box2k2** [comment]
> My other thought, does any mower support `cuttingBladeUsageTime`? Maybe it's just best to remove it

Doesn't appear to be available in the latest Android Flymo app for an Easilife Go 200

**Comment by Marcussjogren** [comment]
> Sorry, I just got back to looking at this.
> 
> I'm assuming that the decoded data `cuttingBladeUsageTime 0` is wrong, so just removing the check isn't enough to get the correct data.
> 
> What I'm assuming is happening is that your model doesn't support `cuttingBladeUsageTime`, as my 305 also has no way to know that information. So I'm guessing that the mower isn't sending the information, hence the 24 bytes. But we currently [expect it](https://github.com/alistair23/AutoMower-BLE/blob/main/automower_ble/protocol.json#L57)
> 
> So we probably need to convert `cuttingBladeUsageTime` to being optional.
> 
> My other thought, does any mower support `cuttingBladeUsageTime`? Maybe it's just best to remove it

Yea I’m well aware that removing the check is not a good solution, but I’m using it like this on my own risk :-)

would be really nice to have it optional or remove it from the 440 model, because i have never seen anything regarding cutting blade time in the app nor in the mowers menu.

**Comment by erikmol** [comment]
> @erikmol any thoughts on removing `cuttingBladeUsageTime`? Does it work for you?

I've seem to kind of brick my BLE connection because my Automower can't be paired with any device so I can't do any testing currently.

When extending the protocol I've been opening a .apk in jadx and "Save as gradle project" and then used file search in VS Code to regex search for major/minor combinations. When looking at `Flymo Bluetooth App_6.1.0_APKPure.apk` I found that the libary code (e.g. `sources\com\gardena\libraries\bluetooth_mower\bluetooth_mower\mowerconnection\commands\StatisticsCommands.java`) is very readable. The following is a snippet from that file and what the `GetAllStatistics` command is based on:

```
        public GetAllStatisticsResponse() {
            super(4726, 0);
            getProtocolData().getParameters().add(new Parameter("totalRunningTime", DataTypes.UINT32));
            getProtocolData().getParameters().add(new Parameter("totalCuttingTime", DataTypes.UINT32));
            getProtocolData().getParameters().add(new Parameter("totalChargingTime", DataTypes.UINT32));
            getProtocolData().getParameters().add(new Parameter("totalSearchingTime", DataTypes.UINT32));
            getProtocolData().getParameters().add(new Parameter("numberOfCollisions", DataTypes.UINT32));
            getProtocolData().getParameters().add(new Parameter("numberOfChargingCycles", DataTypes.UINT32));
            getProtocolData().getParameters().add(new Parameter("cuttingBladeUsageTime", DataTypes.UINT32));
        }
```
I don't think it's relevant to discuss if certain data is used/implemented for specific mowers as we should mimic the protocol. I don't think numberOfChargingCycles is visible in the app either?


Trying to decompile the `Automower Connect_2024.7.1_APKPure.apk` in the same fashion as above does not lead to the same readable and structured code, but I do recognize that there seems to be two implementations of this function:

```
/* compiled from: StatisticsCommands.java */
/* loaded from: classes3.dex */
public class C3 extends O7.b {
    public C3() {
        super(4726, 0);
        c().a().add(new O7.c("totalRunningTime", "uint32"));
        c().a().add(new O7.c("totalCuttingTime", "uint32"));
        c().a().add(new O7.c("totalChargingTime", "uint32"));
        c().a().add(new O7.c("totalSearchingTime", "uint32"));
        c().a().add(new O7.c("numberOfCollisions", "uint32"));
        c().a().add(new O7.c("numberOfChargingCycles", "uint32"));
        c().a().add(new O7.c("cuttingBladeUsageTime", "uint32"));
    }
}
```
and also
```
/* compiled from: StatisticsCommands.java */
/* renamed from: Oe.z3, reason: case insensitive filesystem */
/* loaded from: classes3.dex */
public class C1412z3 extends O7.e {
    public C1412z3() {
        super(4726, 0);
        e().a().add(new O7.c("totalRunningTime", "uint32"));
        e().a().add(new O7.c("totalCuttingTime", "uint32"));
        e().a().add(new O7.c("totalChargingTime", "uint32"));
        e().a().add(new O7.c("totalSearchingTime", "uint32"));
        e().a().add(new O7.c("numberOfCollisions", "uint32"));
        e().a().add(new O7.c("numberOfChargingCycles", "uint32"));
    }
```

So yes, there seems to be two definitions of the same command, the second one lacking the `cuttingBladeUsageTime`.

My suggestion would be to check if the following mappings (all uint32) works, and if so replace the `GetAllStatistics` function. These are also visible in the StatisticsCommands.java file referenced above:
```
4726,1 : "totalRunningTime"
4726,2 : "totalCuttingTime"
4726,3 : "totalChargingTime"
4726,4 : "totalSearchingTime"
4726,5 : "numberOfCollisions"
4726,6 : "numberOfChargingCycles"
4726,7 : "cuttingBladeUsageTime"
```

**Comment by erikmol** [comment]
A side note is that the command `GetTask` have an unknown uint16 appended which also does not match the .apk sources, so maybe some general forgiving processing is prefered for this library?
