### ISSUE TITLE
Mower disconnects as soon as I start the integration

### ISSUE THREAD

**Issue by AlessandroTischer** [alistair23/AutoMower-BLE#9]
I'm having issues connecting to the mower: it seems to connect just fine, until I start the integration process. Then it disconnects and the config flows closes with no error shown. This is the log:

```
2024-04-14 15:20:26.098 DEBUG (MainThread) [custom_components.husqvarna_automower_ble.config_flow] Discovered device: <habluetooth.models.BluetoothServiceInfoBleak object at 0x7f9132446340>
2024-04-14 15:20:26.098 DEBUG (MainThread) [custom_components.husqvarna_automower_ble.config_flow] 00:81:F9:68:E3:60 manufacturer data: {1062: b'\x05\x04\x03\x8f\xd4\n'}
2024-04-14 15:20:26.099 INFO (MainThread) [automower_ble.mower] connecting to device...
  File "/config/custom_components/husqvarna_automower_ble/config_flow.py", line 56, in async_step_bluetooth
  File "/config/custom_components/husqvarna_automower_ble/config_flow.py", line 70, in async_step_confirm
  File "/usr/local/lib/python3.12/site-packages/automower_ble/mower.py", line 217, in probe_gatts
2024-04-14 15:20:43.214 INFO (MainThread) [automower_ble.mower] connecting to device...
2024-04-14 15:20:44.159 INFO (MainThread) [automower_ble.mower] connected
2024-04-14 15:20:44.160 DEBUG (MainThread) [automower_ble.mower] [Service] 00001800-0000-1000-8000-00805f9b34fb (Handle: 1): Generic Access Profile
2024-04-14 15:20:44.317 DEBUG (MainThread) [automower_ble.mower]   [Characteristic] 00002a00-0000-1000-8000-00805f9b34fb (Handle: 3): Device Name (read), Value: bytearray(b'315')
2024-04-14 15:20:44.521 DEBUG (MainThread) [automower_ble.mower]   [Characteristic] 00002a01-0000-1000-8000-00805f9b34fb (Handle: 5): Appearance (read), Value: bytearray(b'\x00\x00')
2024-04-14 15:20:44.639 DEBUG (MainThread) [automower_ble.mower]   [Characteristic] 00002a04-0000-1000-8000-00805f9b34fb (Handle: 7): Peripheral Preferred Connection Parameters (read), Value: bytearray(b'P\x00\xa0\x00\x00\x00\xe8\x03')
2024-04-14 15:20:44.639 DEBUG (MainThread) [automower_ble.mower] [Service] 00001801-0000-1000-8000-00805f9b34fb (Handle: 8): Generic Attribute Profile
2024-04-14 15:20:44.639 DEBUG (MainThread) [automower_ble.mower] [Service] 98bd0001-0b0e-421a-84e5-ddbf75dc6de4 (Handle: 9): Husqvarna
2024-04-14 15:20:44.640 DEBUG (MainThread) [automower_ble.mower]   [Characteristic] 98bd0002-0b0e-421a-84e5-ddbf75dc6de4 (Handle: 11): Unknown (write-without-response)
2024-04-14 15:20:44.726 ERROR (MainThread) [automower_ble.mower]   [Characteristic] 98bd0003-0b0e-421a-84e5-ddbf75dc6de4 (Handle: 14): Unknown (read,notify), Error: Bluetooth GATT Error address=00:81:F9:68:E3:60 handle=14 error=15 description=Insufficient encryption
2024-04-14 15:20:44.870 DEBUG (MainThread) [automower_ble.mower]   [Characteristic] 98bd0004-0b0e-421a-84e5-ddbf75dc6de4 (Handle: 18): Unknown (read), Value: bytearray(b'Automower\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00')
``` 

I have a 315 with security level set to low, but it still has a pin set (it's not possible to remove it).

**Comment by alistair23** [comment]
Did you follow https://github.com/alistair23/AutoMower-BLE/issues/6#issuecomment-2041446259?

Obviously enter the PIN at the mower as well once you turn it on

**Comment by AlessandroTischer** [comment]
> Did you follow https://github.com/alistair23/AutoMower-BLE/issues/6#issuecomment-2041446259?
> 
> Obviously enter the PIN at the mower as well once you turn it on

Yes, I'm doing it just like that...

**Comment by alistair23** [comment]
Can you test locally with a PC? See if it works if you supply the PIN

**Comment by AlessandroTischer** [comment]
> Can you test locally with a PC? See if it works if you supply the PIN

Sorry but could you explain me how to do so? I'm not sure I understand what you are asking me to do...

**Comment by alistair23** [comment]
Run the scripts on a local PC (see https://github.com/alistair23/AutoMower-BLE?tab=readme-ov-file#testing-connections) and modify the connection to set the PIN before trying to get the status

**Comment by AlessandroTischer** [comment]
> Run the scripts on a local PC (see https://github.com/alistair23/AutoMower-BLE?tab=readme-ov-file#testing-connections) and modify the connection to set the PIN before trying to get the status

I'm not familiar with python, but I tried with the following steps:

- Downloaded this repository
- run `python3 request.py`
- I had some problems with importing the files, I found out they can be solved changing (for example) `from .helpers import crc` in `from helpers import crc`.
- I still cannot solve 
- `./mower.py --address 00:81:F9:68:E3:60
- Traceback (most recent call last):
-   File "...\AutoMower-BLE-main\automower_ble\mower.py", line 18, in <module>
-     from bleak import BleakClient, BleakScanner
- ModuleNotFoundError: No module named 'bleak'`

Most importantly, though, I'm not sure how to test the connection and set the pin.

Sorry to bother you, and thank you again for all the effort and time you're spending....

**Comment by erikmol** [comment]
> I'm not familiar with python, but I tried with the following steps:

You should be running `mower.py`, not the unit tests, see the header "Testing Connections"

If you instead stand in the parent directory (i.e. where you find the README.md) you can run
`python3 -m automower_ble.mower --address AB:CD:12:34...`
and there is no need to modify the imports.


> `ModuleNotFoundError: No module named 'bleak'`

You need to install `bleak` using `pip install bleak` or `pip3 install bleak` 

> Most importantly, though, I'm not sure how to test the connection and set the pin.

Yeah this is not straight-forward as there is need to modify the code within `mower.py` to get the `MowerRequest.generate_request_pin` function in there somewhere. Probably requires someone with decent python skills along with the mower of interest.

**Comment by alistair23** [comment]
> > 
> 
> Yeah this is not straight-forward as there is need to modify the code within `mower.py` to get the `MowerRequest.generate_request_pin` function in there somewhere. Probably requires someone with decent python skills along with the mower of interest.

You should just be able to call this after connecting. It's really just up to someone who has a 315 to try this to figure out what works.

**Comment by AlessandroTischer** [comment]
```
>python3 -m automower_ble.mower --address 00:81:F9:68:E3:60
2024-04-19 16:54:53,424 __main__ INFO: starting scan...
2024-04-19 16:54:53,427 __main__ INFO: connecting to device...
2024-04-19 16:54:55,429 __main__ INFO: connected
2024-04-19 16:54:55,429 __main__ INFO: pairing device...
2024-04-19 16:54:56,509 bleak.backends.winrt.client INFO: Paired to device with protection level <DevicePairingProtectionLevel.NONE: 1>.
2024-04-19 16:54:56,515 __main__ INFO: paired
2024-04-19 16:54:56,529 __main__ INFO: [Service] 98bd0001-0b0e-421a-84e5-ddbf75dc6de4 (Handle: 9): Unknown
2024-04-19 16:55:01,692 __main__ INFO: Writing: b'02fd160000000000002e14b63b6047000000004d61696e001203'
2024-04-19 16:55:01,985 __main__ INFO: Received: b'02fd0d0000000000006315b63b6047b603'
2024-04-19 16:55:01,987 __main__ INFO: Final response: b'02fd0d0000000000006315b63b6047b603'
2024-04-19 16:55:01,987 __main__ INFO: Writing: b'02fd0a00b63b6047008f08012803'
2024-04-19 16:55:02,105 __main__ INFO: Received: b'02fd0b00b63b604700b20901011403'
2024-04-19 16:55:02,107 __main__ INFO: Final response: b'02fd0b00b63b604700b20901011403'
2024-04-19 16:55:02,107 __main__ INFO: Writing: b'02fd1000b63b604701a100af5a1209000000b703'
2024-04-19 16:55:02,284 __main__ INFO: Received: b'02fd1300b63b604701e601af5a1209000002000c'
2024-04-19 16:55:02,284 __main__ INFO: Received: b'005903'
2024-04-19 16:55:02,286 __main__ INFO: Final response: b'02fd1300b63b604701e601af5a1209000002000c005903'
Connected to: 315
2024-04-19 16:55:02,287 __main__ INFO: Writing: b'02fd1000b63b604701a100af0a10150000003003'
2024-04-19 16:55:02,403 __main__ INFO: Received: b'02fd1200b63b604701db01af0a10150000010000'
2024-04-19 16:55:02,405 __main__ INFO: Received: b'4803'
2024-04-19 16:55:02,407 __main__ INFO: Final response: b'02fd1200b63b604701db01af0a101500000100004803'
Mower is not charging
2024-04-19 16:55:02,407 __main__ INFO: Writing: b'02fd1000b63b604701a100af0a1014000000bf03'
2024-04-19 16:55:02,524 __main__ INFO: Received: b'02fd1200b63b604701db01af0a10140000010063'
2024-04-19 16:55:02,525 __main__ INFO: Received: b'f803'
2024-04-19 16:55:02,526 __main__ INFO: Final response: b'02fd1200b63b604701db01af0a10140000010063f803'
Battery is: 99%
2024-04-19 16:55:02,526 __main__ INFO: Writing: b'02fd1000b63b604701a100afea11020000006a03'
2024-04-19 16:55:02,643 __main__ INFO: Received: b'02fd1200b63b604701db01afea11020000010006'
2024-04-19 16:55:02,646 __main__ INFO: Received: b'0503'
2024-04-19 16:55:02,648 __main__ INFO: Final response: b'02fd1200b63b604701db01afea110200000100060503'
Mower state: checkSafety
2024-04-19 16:55:02,648 __main__ INFO: Writing: b'02fd1000b63b604701a100afea1103000000e503'
2024-04-19 16:55:02,764 __main__ INFO: Received: b'02fd1200b63b604701db01afea11030000010003'
2024-04-19 16:55:02,765 __main__ INFO: Received: b'0d03'
2024-04-19 16:55:02,766 __main__ INFO: Final response: b'02fd1200b63b604701db01afea110300000100030d03'
Mower activity: mowing
2024-04-19 16:55:02,885 __main__ INFO: disconnecting...
2024-04-19 16:55:06,253 __main__ INFO: disconnected
```


> You should just be able to call this after connecting. It's really just up to someone who has a 315 to try this to figure out what works.

Honestly I don't know how to interpret these logs...

**Comment by alistair23** [comment]
Great! So a PIN isn't required, same as the 305.

So the `Insufficient encryption` you get from HA is because you have not paired the mower to the BLE controller you are using

**Comment by AlessandroTischer** [comment]
> Great! So a PIN isn't required, same as the 305.
> 
> So the `Insufficient encryption` you get from HA is because you have not paired the mower to the BLE controller you are using

Right, but what am I doing differently with the esp proxy?

**Comment by alistair23** [comment]
Good question... Maybe the full log provides more details as to what is going on? What does your ESPHome config look like?

**Comment by AlessandroTischer** [comment]
> Good question... Maybe the full log provides more details as to what is going on? 

What do you need me to get? [This](https://github.com/alistair23/AutoMower-BLE/issues/9#issue-2242172059) is the log I get in HA, if you need more just tell me what to look for👍 

>What does your ESPHome config look like?
```
esphome:
  name: general-power-meter

esp32:
  board: esp32dev
  framework:
    type: esp-idf


# Enable logging
logger:

# Enable Home Assistant API
api:

web_server:
  port: 80

ota:
  password: "7c07b50a38c6fa88323adaea9f9c9703"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.188.195
    gateway: 192.168.188.1
    subnet: 255.255.255.0
  use_address: 192.168.188.195


  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "General-Power-Meter"
    password: ####



esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true
    continuous: true

bluetooth_proxy:
  active: true
  cache_services: false

ble_client:
    - mac_address: 00:81:F9:68:E3:60
      id:  automower_315

button:
  - platform: restart
    name: "ESP restart"
  - platform: template
    name: "ESP start Scan"
    on_press:
      - esp32_ble_tracker.start_scan:
```

**Comment by alistair23** [comment]
> What do you need me to get? [This](https://github.com/alistair23/AutoMower-BLE/issues/9#issue-2242172059) is the log I get in HA, if you need more just tell me what to look for👍

The full log is the entire log file, this is just a little snippet.

You can try removing the `ble_client` section from the config. I have seen somewhere else that it shouldn't actually be needed.

**Comment by phoffi** [comment]
Thank you for this information, that was my solution too. I removed the `ble_client` section, and my Husqvarna 420 added without any "`Insufficient encryption`" errors and PIN requirements.
